export { default as BACK_ARROW } from './backArrow.svg';
export { default as CHECKED } from './checked.svg';
export { default as INFO_ICON } from './informationIcon.svg';
export { default as MINUS } from './minusIcon.svg';
export { default as PLUS } from './plusIcon.svg';
export { default as UNCHECKED } from './unchecked.svg';
export { default as EMPTY_CART } from './emptyCart.svg';
export { default as WARNING } from './warning.svg';
export { default as LOGO } from './logo.svg';
