const ACTION_TYPE = {
  ADD_PRODUCT_TO_CART: 'ADD_PRODUCT_TO_CART',
  SUBTRACT_CART_PRODUCT_QUANTITY: 'SUBTRACT_CART_PRODUCT_QUANTITY',
  REMOVE_PRODUCT_FROM_CART: 'REMOVE_PRODUCT_FROM_CART',
};

export default ACTION_TYPE;
