const CART_ACTIONS = {
  PUT: 'cart/PUT',
  DELETE: 'cart/DELETE',
  SELECTIVE_DELETE: 'cart/SELECTIVE_DELETE',
};

const PRODUCT_LIST_ACTIONS = {
  INITIALIZE: 'productList/INITIALIZE',
};

const ORDER_ACTIONS = {
  ADD: 'order/ADD',
  DELETE: 'order/DELETE',
  INITIALIZE: 'order/INITIALIZE',
};

export { CART_ACTIONS, PRODUCT_LIST_ACTIONS, ORDER_ACTIONS };
