const CART_INITIALIZE = 'cart/INITIALIZE';
const CART_PUT = 'cart/PUT';
const CART_SELECT = 'cart/SELECT';

const PRODUCT_INITIALIZE = 'productList/INITIALIZE';

export { CART_INITIALIZE, CART_PUT, CART_SELECT, PRODUCT_INITIALIZE };
