const CART_INITIALIZE = 'cart/INITIALIZE';
const CART_PUT = 'cart/PUT';
const CART_SELECT = 'cart/SELECT';
const CART_DELETE = 'cart/DELETE';

const PRODUCT_INITIALIZE = 'productList/INITIALIZE';

export { CART_INITIALIZE, CART_PUT, CART_SELECT, CART_DELETE, PRODUCT_INITIALIZE };
