const PRODUCTS_ACTIONS = {
  UPDATE_PRODUCT_LIST: 'UPDATE_PRODUCT_LIST',
  UPDATE_PRODUCT_LIST_SUCCESS: 'UPDATE_PRODUCT_LIST_SUCCESS',
  UPDATE_PRODUCT_LIST_ERROR: 'UPDATE_PRODUCT_LIST_ERROR',
};

const CARTS_ACTIONS = {
  ADD_CART_LIST: Symbol('장바구니에 상품을 추가합니다.'),
};

export { PRODUCTS_ACTIONS, CARTS_ACTIONS };
