const PRODUCTS_ACTIONS = {
  UPDATE_PRODUCT_LIST_PENDING: 'UPDATE_PRODUCT_LIST_PENDING',
  UPDATE_PRODUCT_LIST_SUCCESS: 'UPDATE_PRODUCT_LIST_SUCCESS',
  UPDATE_PRODUCT_LIST_ERROR: 'UPDATE_PRODUCT_LIST_ERROR',
};

const CARTS_ACTIONS = {
  UPDATE_CART_LIST_PENDING: 'UPDATE_CART_LIST_PENDING',
  UPDATE_CART_LIST_SUCCESS: 'UPDATE_CART_LIST_SUCCESS',
  UPDATE_CART_LIST_ERROR: 'UPDATE_CART_LIST_ERROR',

  ADD_CART_LIST_PENDING: 'ADD_CART_LIST_PENDING',
  ADD_CART_LIST_SUCCESS: 'ADD_CART_LIST_SUCCESS',
  ADD_CART_LIST_ERROR: 'ADD_CART_LIST_ERROR',

  UPDATE_CART_ITEM_SUCCESS: 'UPDATE_CART_ITEM_SUCCESS',
  UPDATE_CART_ITEM_CHECKED: 'UPDATE_CART_ITEM_CHECKED',

  REMOVE_CART_ITEM_SUCCESS: 'REMOVE_CART_ITEM_SUCCESS',
};

export { PRODUCTS_ACTIONS, CARTS_ACTIONS };
