const PRODUCTS_ACTIONS = {
  UPDATE_PRODUCT_LIST: 'UPDATE_PRODUCT_LIST',
  UPDATE_PRODUCT_LIST_SUCCESS: 'UPDATE_PRODUCT_LIST_SUCCESS',
  UPDATE_PRODUCT_LIST_ERROR: 'UPDATE_PRODUCT_LIST_ERROR',
};

const CARTS_ACTIONS = {
  ADD_CART_LIST: 'ADD_CART_LIST',
};

export { PRODUCTS_ACTIONS, CARTS_ACTIONS };
