const CART_LIST_LOCAL_STORAGE_KEY = 'cartList';

const ESC_KEY = 'Escape';

const DEFAULT_MIN_COUNT = 1;
const DEFAULT_MAX_COUNT = 99;
const DEFAULT_STEP = 1;

const TOAST_SHOW_DURATION = 2000;

const PRODUCT_LIST_SKELETON_ITEM_LENGTH = 15;

export {
  CART_LIST_LOCAL_STORAGE_KEY,
  ESC_KEY,
  DEFAULT_MIN_COUNT,
  DEFAULT_MAX_COUNT,
  DEFAULT_STEP,
  TOAST_SHOW_DURATION,
  PRODUCT_LIST_SKELETON_ITEM_LENGTH,
};
