const CART_LIST_LOCAL_STORAGE_KEY = 'cartList';

const ESC_KEY = 'Escape';

const STEPPER_BUTTON_MIN_COUNT = 1;
const STEPPER_BUTTON_MAX_COUNT = 99;

export { CART_LIST_LOCAL_STORAGE_KEY, ESC_KEY, STEPPER_BUTTON_MIN_COUNT, STEPPER_BUTTON_MAX_COUNT };
