const ALERT_MESSAGE_MAX_NUM = 3;
const ALERT_MESSAGE_DURATION = 3000;

const ERROR_MESSAGE = {
  API_CALL: "Api Call Error",
}

export { ALERT_MESSAGE_MAX_NUM, ALERT_MESSAGE_DURATION, ERROR_MESSAGE };