const FREE_DELIVERY_THRESHOLD = 100000;
const DEFAULT_SHIPPING_FEE = 3000;
const ADDITIONAL_SHIPPING_FEE = 6000;
const MAX_COUPON_COUNT = 2;

export {
  FREE_DELIVERY_THRESHOLD,
  DEFAULT_SHIPPING_FEE,
  ADDITIONAL_SHIPPING_FEE,
  MAX_COUPON_COUNT,
};
