export const TEXT = {
  DELETE: '삭제',
  COUPON: '쿠폰 적용',
  DELIVERY_INFO: '배송 정보',
  DELIVERY_INFO_DESCRIPTION: '제주도 및 도서 산간 지역',
  ALL_SELECT: '전체 선택',
  CART_TITLE: '장바구니',
  ORDER_PRICE: '주문 금액',
  DELIVERY_FEE: '배송비',
  TOTAL_PRICE: '총 결제 금액',
  ORDER_CHECK: '주문 확인',
  PAY: '결제하기',
  NO_PRODUCT: '장바구니에 담은 상품이 없습니다.',
  TOTAL_PRICE_CHECK_MESSAGE: '최종 결제 금액을 확인해 주세요.',
};
