const ADD_SHOPPING_CART_ITEMS = 'ADD_MY_SHOPPING_CART_ITEMS';
const REMOVE_SHOPPING_CART_ITEMS = 'REMOVE_SHOPPING_CART_ITEMS';
const INCREASE_PRODUCT_AMOUNT = 'INCREASE_PRODUCT_AMOUNT';
const DECREASE_PRODUCT_AMOUNT = 'DECREASE_PRODUCT_AMOUNT';
const CHECK_PRODUCT = 'CHECK_PRODUCT';
const UNCHECK_PRODUCT = 'UNCHECK_PRODUCT';
const UPDATE_PRODUCT_LIST = 'UPDATE_PRODUCT_LIST';
const ACTIVATE_LOADING_SPINNER = 'ACTIVATE_LOADING_SPINNER';
const DEACTIVATE_LOADING_SPINNER = 'DEACTIVATE_LOADING_SPINNER';
const TOGGLE_LIKE_PRODUCT = 'TOGGLE_LIKE_PRODUCT';
const INCREASE_PAGE_INDEX = 'INCREASE_PAGE_INDEX';
const DECREASE_PAGE_INDEX = 'INCREASE_PDECREASE_PAGE_INDEXAGE_INDEX';
const INIT_PAGE_INDEX = 'INIT_PAGE_INDEX';

export {
  ADD_SHOPPING_CART_ITEMS,
  REMOVE_SHOPPING_CART_ITEMS,
  CHECK_PRODUCT,
  UNCHECK_PRODUCT,
  INCREASE_PRODUCT_AMOUNT,
  UPDATE_PRODUCT_LIST,
  DECREASE_PRODUCT_AMOUNT,
  ACTIVATE_LOADING_SPINNER,
  DEACTIVATE_LOADING_SPINNER,
  INCREASE_PAGE_INDEX,
  DECREASE_PAGE_INDEX,
  INIT_PAGE_INDEX,
  TOGGLE_LIKE_PRODUCT,
};
