const ADD_SHOPPING_CART_ITEM = 'ADD_SHOPPING_CART_ITEM';
const DELETE_SHOPPING_CART_ITEM = 'DELETE_SHOPPING_CART_ITEM';
const DELETE_SHOPPING_CART_ITEMS = 'DELETE_SHOPPING_CART_ITEMS';
const GET_MY_SHOPPING_CART = 'GET_MY_SHOPPING_CART';
const INCREASE_AMOUNT = 'INCREASE_AMOUNT';
const DECREASE_AMOUNT = 'DECREASE_AMOUNT';

export {
  ADD_SHOPPING_CART_ITEM,
  DELETE_SHOPPING_CART_ITEM,
  DELETE_SHOPPING_CART_ITEMS,
  GET_MY_SHOPPING_CART,
  INCREASE_AMOUNT,
  DECREASE_AMOUNT,
};
