const ADD_ITEM = 'ADD_ITEM';
const GET_ALL_ITEMS = 'GET_ALL_ITEMS';
const DELETE_ITEMS = 'DELETE_ITEMS';
const GET_MY_SHOPPING_CART = 'GET_MY_SHOPPING_CART';
const UPDATE_MY_SHOPPING_CART_ITEMS = 'UPDATE_MY_SHOPPING_CART_ITEMS';

export { ADD_ITEM, GET_ALL_ITEMS, DELETE_ITEMS, GET_MY_SHOPPING_CART, UPDATE_MY_SHOPPING_CART_ITEMS };
