const ACTION_TYPE = {
  ADD_PRODUCT_TO_CART: "ADD_PRODUCT_TO_CART",
  UPDATE_PRODUCT_LIST: "UPDATE_PRODUCT_LIST",
  SELECT_PRODUCT_IN_CART: "SELECT_PRODUCT_IN_CART",
  DESELECT_PRODUCT_IN_CART: "DESELECT_PRODUCT_IN_CART",
  SELECT_ALL_PRODUCTS_IN_CART: "SELECT_ALL_PRODUCTS_IN_CART",
  DESELECT_ALL_PRODUCTS_IN_CART: "DESELECT_ALL_PRODUCTS_IN_CART",
  UPDATE_PRODUCT_QUANTITY_IN_CART: "UPDATE_PRODUCT_QUANTITY_IN_CART",
  DELETE_PRODUCT_IN_CART: "DELETE_PRODUCT_IN_CART",
  DELETE_MULTIPLE_PRODUCTS_IN_CART: "DELETE_MULTIPLE_PRODUCTS_IN_CART",
};

export default ACTION_TYPE;
