export const GET_PRODUCT_LIST_START = "GET_PRODUCT_LIST_START";
export const GET_PRODUCT_LIST_SUCCESS = "GET_PRODUCT_LIST_SUCCESS";
export const GET_PRODUCT_LIST_ERROR = "GET_PRODUCT_LIST_ERROR";

export const ADD_PRODUCT_TO_CART = "ADD_PRODUCT_TO_CART";
export const TOGGLE_CART_ITEM_CHECK_BUTTON = "TOGGLE_CART_ITEM_CHECK_BUTTON";
export const UNCHECK_ALL_CHECK_BUTTON = "UNCHECK_ALL_CHECK_BUTTON";
export const CHECK_ALL_CHECK_BUTTON = "CHECK_ALL_CHECK_BUTTON";
export const INCREMENT_CART_ITEM_QUANTITY = "INCREMENT_CART_ITEM_QUANTITY";
export const DECREMENT_CART_ITEM_QUANTITY = "DECREMENT_CART_ITEM_QUANTITY";
export const REMOVE_CHECKED_CART_ITEM = "REMOVE_CHECKED_CART_ITEM";
export const REMOVE_ROW_CART_ITEM = "REMOVE_ROW_CART_ITEM";
