export const actionTypes = {
  SET_CART_PRODUCT_LIST: 'SET_CART_PRODUCT_LIST',
  ADD_PRODUCT_TO_CART: 'ADD_PRODUCT_TO_CART',
  REMOVE_PRODUCT_TO_CART: 'REMOVE_PRODUCT_TO_CART',
  REMOVE_PRODUCTS_TO_CART: 'REMOVE_PRODUCTS_TO_CART',
  UN_CHECK: 'UN_CHECK',
  CHECK: 'CHECK',
  ALL_CHECK: 'ALL_CHECK',
  ALL_UN_CHECK: 'ALL_UN_CHECK',
};
